esp8266:
    defs:
        - CMAKE_TOOLCHAIN_FILE=../../cmake/esp8266-open-rtos.cmake
        - CMAKE_SYSTEM_NAME=Generic
        - ESP8266_TOOLCHAIN_PATH=~/usr/xtensa-lx106-elf
        - ESP8266_OPEN_RTOS_PATH=~/usr/esp8266-open-rtos
        - CMAKE_C_COMPILER=xtensa-lx106-elf-gcc
        - CMAKE_CXX_COMPILER=xtensa-lx106-elf-g++
        - CONFIG_NO_SYS=True
        - FREERTOS=True
        - FREERTOS_MANUAL=True
        - RTTI=False
        - CONFIG_TASK_PRIO=6
        - CONFIG_STACK_SIZE=4096
        - CONFIG_PIN_VECTOR=True

esp32:
    defs:
        - CMAKE_TOOLCHAIN_FILE=../../cmake/esp32.cmake
        - CMAKE_SYSTEM_NAME=Generic
        - ESP32_TOOLCHAIN_PATH=/opt/xtensa-esp32-elf
        - CMAKE_C_COMPILER=xtensa-esp32-elf-gcc
        - CMAKE_CXX_COMPILER=xtensa-esp32-elf-g++
        - CONFIG_NO_SYS=True
        - FREERTOS=True
        - FREERTOS_MANUAL=True
        - RTTI=False
        - CONFIG_TASK_PRIO=6
        - CONFIG_STACK_SIZE=4096
        - CONFIG_PIN_VECTOR=True
        - CONFIG_PATCH_I2C_CLOCK=True

freertos:
    defs:
        - UNIX=True
        - FREERTOS=True
        - CONFIG_NO_SYS=False
        - PORT=unix
        - CMAKE_SYSTEM_NAME=Generic
        - CONFIG_TASK_PRIO=6

unix:
    defs:
        - CONFIG_NO_SYS=False
        - HAVE_NETWORKING=True
        - HAVE_DEBUG=True
        - HAVE_JSON=True
        - CONFIG_BUILD_TESTS=True
        - CONFIG_STACK_SIZE=4096
        - CONFIG_PIN_VECTOR=True

win32:
    defs:
        - CONFIG_NO_SYS=False
        - CONFIG_PIN_VECTOR=True
        - HAVE_DEBUG=True
        - CONFIG_BUILD_TESTS=True
        
atmega2560:
    defs:
        - AVR=True
        - MCU=atmega2560
        - CMAKE_C_COMPILER=avr-gcc
        - CMAKE_CXX_COMPILER=avr-g++
        - CONFIG_NO_SYS=True
        - CMAKE_SYSTEM_NAME=Generic
        - CMAKE_TOOLCHAIN_FILE=../../cmake/avr.cmake
        - FREERTOS=True
        - FREERTOS_MANUAL=True
        - F_CPU=16000000
        - ARDUINO_MEGA=True
        - CONFIG_TASK_PRIO=6
        - CONFIG_STACK_SIZE=4096
        - CONFIG_PIN_VECTOR=True

atmega328:
    defs:
        - AVR=True
        - CMAKE_C_COMPILER=avr-gcc
        - CMAKE_CXX_COMPILER=avr-g++
        - MCU=atmega328
        - CMAKE_TOOLCHAIN_FILE=../../cmake/avr.cmake
        - CONFIG_NO_SYS=True
        - CMAKE_SYSTEM_NAME=Generic
        - CONFIG_STANDALONE=True
        - F_CPU=16000000
        - ARDUINO_UNO=True
